version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pytest --cov-fail-under=70 --cov=./
  post_build:
    commands:
      - rm -R tests
artifacts:
  files:
    - '**/*'
