branch-defaults:
  Entrega2:
    environment: ListaNegraApp-env
    group_suffix: null
global:
  application_name: listaNegraApp
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9
  default_region: us-east-2
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
